### PR TITLE
Setup `go mod`

### PR DESCRIPTION
**Pull request by earlgreyz**

### CODE REVIEW

**Comment by earlgreyz** [comment]
The broken build is unrelated and is fixed in https://github.com/facebookincubator/fbender/pull/17

**Comment by fabriziocucci** [comment]
Don't we need to update the GitHub Action to use `go mod download` to get the dependencies?

**Comment by earlgreyz** [comment]
Fixed.

**Comment by fabriziocucci** [comment]
Thanks @earlgreyz for this amazing contribution! :neckbeard:

**Pull request closed without merging**
